// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4d172ae1-9eeb-44f0-98e0-e4211ce9c338",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_PHbWQlVKc",
    "aws_user_pools_web_client_id": "5ls5gd8fnfbavnadjf0kle251v",
    "aws_user_files_s3_bucket": "amplifystoragebucket3141",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
