#!/usr/bin/env bash

# Setup swap, if none
haveSwap() {
    swapon --summary | awk '{print $3}' | grep -oP '[0-9]+' > /dev/null
}

makeSwap() {
    sudo fallocate -l 2G /swapfile || exit 1
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    sudo sed -ie '$a/swapfile swap swap defaults 0 0' /etc/fstab
}

if ! haveSwap; then
    makeSwap
fi

# Anthonyize
cd ~
mkdir -p Git
cd Git
git clone https://github.com/AnthonyD973/Anthonyize
. Anthonyize/anthonyize

# Setup npm and npm packages
sudo apt update -y
sudo apt upgrade -y
sudo apt install npm -y
sudo npm install -g npm@latest
sudo npm install -g nodejs@latest
sudo npm install -g @angular/cli
sudo npm install -g @aws-amplify/cli
sudo npm install -g node-gyp

# Setup Sandbox
if [ ! -d "$HOME/Git/Sandbox" ]; then
    cd ~/Git
    git clone https://github.com/AnthonyD973/Sandbox
fi
cd ~/Git/Sandbox
git checkout amazonaws-branch
cd ~/Git/Sandbox/AmazonAws/client/AmazonAwsClient
npm install

# Apply changes to bash.
# Must be the last command, since this script will stop after it.
exec bash
